# Generated by Django 6.0 on 2025-12-04 19:31

from django.db import migrations
from datetime import time

def create_medicos(apps, schema_editor):
    Medico = apps.get_model('core', 'Medico')
    Medico.objects.bulk_create([
        Medico(nome='Dr. Ana Souza', especialidade='Cardiologia', horario_inicio_atendimento=time(8, 0), horario_fim_atendimento=time(12, 0)),
        Medico(nome='Dr. Carlos Mendes', especialidade='Dermatologia', horario_inicio_atendimento=time(13, 0), horario_fim_atendimento=time(17, 0)),
        Medico(nome='Dra. Beatriz Lima', especialidade='Pediatria', horario_inicio_atendimento=time(9, 0), horario_fim_atendimento=time(16, 0)),
    ])

def reverse_medicos_creation(apps, schema_editor):
    Medico = apps.get_model('core', 'Medico')
    Medico.objects.filter(
        nome__in=['Dr. Ana Souza', 'Dr. Carlos Mendes', 'Dra. Beatriz Lima']
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_medicos, reverse_medicos_creation),
    ]

